[package]
name = "bindings"
version = "0.1.0"
edition = "2024"

[dependencies]
wasmtime = { version = "32", default-features = false }
wit-bindgen = { version = "0.41", default-features = false, features = [
    "macros",
] }
wit-bindgen-rt = { version = "0.41", default-features = false }
